//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_handler_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopifyCredential
    {
        public System.Guid ID { get; set; }
        public string APIKey { get; set; }
        public string Password { get; set; }
        public string HostName { get; set; }
    }
}
