//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_handler_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SalesTargetHistory> SalesTargetHistories { get; set; }
        public virtual DbSet<ShopifyCredential> ShopifyCredentials { get; set; }
        public virtual DbSet<StoreCustomData> StoreCustomDatas { get; set; }
        public virtual DbSet<SalesData> SalesDatas { get; set; }
        public virtual DbSet<LastShopifyDataUpdate> LastShopifyDataUpdates { get; set; }
        public virtual DbSet<AliasType> AliasTypes { get; set; }
        public virtual DbSet<StoreAlias> StoreAliases { get; set; }
    }
}
