//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_handler_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreCustomData
    {
        public int StoreID { get; set; }
        public Nullable<System.Guid> ShopifyID { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> SalesTarget { get; set; }
    }
}
